// frontend/generate-config.js
const fs = require('fs');
const path = require('path');

// Get API_URL from environment or use placeholder
const apiUrl = process.env.API_URL || 'https://your-backend.onrender.com/api/check-balances';

const configContent = `// Auto-generated by generate-config.js
window.API_URL = '${apiUrl}';
`;

const outputPath = path.join(__dirname, 'js', 'config.js');

try {
  // Ensure js directory exists
  const jsDir = path.join(__dirname, 'js');
  if (!fs.existsSync(jsDir)) {
    fs.mkdirSync(jsDir, { recursive: true });
  }
  
  fs.writeFileSync(outputPath, configContent);
  console.log('✅ Config generated successfully');
  console.log(`API_URL: ${apiUrl}`);
} catch (error) {
  console.error('❌ Error generating config:', error.message);
  process.exit(1);
}