// frontend/generate-config.js
const fs = require('fs');
const path = require('path');

// Get API_URL from environment or use placeholder
const apiUrl = process.env.API_URL || 'https://your-backend.onrender.com/api/check-balances';

// Validate URL format
try {
  const parsedUrl = new URL(apiUrl);
  if (!parsedUrl.protocol.startsWith('http')) {
    throw new Error('API_URL must start with http:// or https://');
  }
} catch (error) {
  console.error('❌ Invalid API_URL format:', apiUrl);
  console.error('Error:', error.message);
  process.exit(1);
}

const configContent = `// Auto-generated by generate-config.js
// Generated at: ${new Date().toISOString()}
// Do not edit manually - Changes will be overwritten

(function() {
  const API_URL = '${apiUrl}';
  
  // Set both formats for compatibility
  window.APP_CONFIG = {
    API_URL: API_URL
  };
  window.API_URL = API_URL;
  
  console.log('✅ Config loaded. API URL:', API_URL);
})();
`;

const outputPath = path.join(__dirname, 'js', 'config.js');

try {
  // Ensure js directory exists
  const jsDir = path.join(__dirname, 'js');
  if (!fs.existsSync(jsDir)) {
    fs.mkdirSync(jsDir, { recursive: true });
  }
  
  fs.writeFileSync(outputPath, configContent);
  console.log('✅ Config generated successfully');
  console.log(`📁 Output: ${outputPath}`);
  console.log(`🔗 API_URL: ${apiUrl}`);
} catch (error) {
  console.error('❌ Error generating config:', error.message);
  process.exit(1);
}